sena/sena/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('territorio/', include('territorio.urls')),
]

sena/territorio/urls.py
from django.urls import path
from . import views

app_name='territorio'

urlpatterns = [
    path("", views.index, name="index"),

    #Rutas aprendices
    path("aprendiz/", views.aprendiz, name="listar-aprendices"),
    path("crear-aprendiz/", views.aprendicesForm, name="crearAprendices"),
    path("guardar-aprendiz/", views.aprendicesGuardar, name="guardarAprendices"),

    #Rutas monitorias
    path("monitorias/", views.listarMonitoria, name="listar-monitoria"),
    path("crear-monitorias/", views.monitoriasForm, name="crearMonitoria"),
    path("guardar-monitorias/", views.monitoriasGuardar, name="monitoriasGuardar"),

    #Rutas actividades
    path("actividades/", views.listarActividades, name="listar-actividades"),
]

sena/territorio/models.py
from django.db import models

# Create your models here.

class Aprendiz(models.Model):
    cedula = models.IntegerField()
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        return self.nombre

class Monitoria(models.Model):
    cat = models.CharField(max_length=100)
    aprendiz = models.ForeignKey(Aprendiz, on_delete = models.DO_NOTHING)
    fecha_Inicio = models.DateTimeField()
    fecha_Final = models.DateTimeField() 

    def __str__(self):
        return f"{self.aprendiz} - {self.cat}"

class Actividades(models.Model):
    monitor = models.ForeignKey(Monitoria, on_delete=models.DO_NOTHING)
    actividad_Realizada = models.CharField(max_length=100)
    obs = models.TextField()
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.actividad_Realizada

sena/territorio/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Aprendiz, Monitoria, Actividades 
from django.urls import reverse

# Create your views here.

def index(request):
    return render(request, "territorio/index.html")

#CRUD aprendices

def aprendiz(request):
    q = Aprendiz.objects.all()
    context = {'datos':q}
    return render(request, "territorio/aprendiz/listarAprendiz.html", context)

def aprendicesForm(request):
    return render(request, "territorio/aprendiz/formAprendiz.html")

def aprendicesGuardar(request):
    try:
        q = Aprendiz(
            cedula = request.POST['cedula'],
            nombre = request.POST['nombre'],
            apellido = request.POST['apellido'],
            fecha_nacimiento = request.POST['fecha_nacimiento']
        )
        q.save()
        #return HttpResponse("Aprendiz guardado <br/> <a href='../aprendiz/'>Listar aprendiz</a>")
        return HttpResponseRedirect(reverse('territorio:aprendices'))
    except Exception as e:
        return HttpResponse("Error: " + str(e))


#CRUD monitorias

def listarMonitoria(request):
    m = Monitoria.objects.all()
    context = {'datosM':m}
    return render(request, "territorio/monitoria/listarMonitoria.html", context)

def monitoriasForm(request):
    m = Aprendiz.objects.all()
    context = {'datos':m}
    return render(request, "territorio/monitoria/formMonitoria.html", context)

def monitoriasGuardar(request):
    try:
        a = Aprendiz.objects.get(pk = request.POST['aprendiz'])

        q = Monitoria(
            cat = request.POST['cat'],
            aprendiz = a,
            fecha_Inicio = request.POST['fecha_Inicio'],
            fecha_Final = request.POST['fecha_Final']
        )
        q.save()

        """
            cat = request.POST['cat'],
            aprendiz = request.POST['aprendiz']
            fecha_Inicio = request.POST['fecha_Inicio'],
            fecha_Final = request.POST['fecha_Final']

            a = Aprendiz.objects.get(id='aprendiz')
            crear = Monitoria.objects.create(cat=cat, aprendiz=a, fecha_Inicio,fecha_Final)
        
        """
        return HttpResponseRedirect(reverse('territorio:listar-monitoria'))
    except Exception as e:
        return HttpResponse("Error" + str(e))


#CRUD actividades

def listarActividades(request):
    ac = Actividades.objects.all()
    context = {'datosAc':ac}
    return render(request, "territorio/actividades/listarActividades.html", context)

sena/territorio/templates/territorio/actividades/listarActividades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar actividades</title>
</head>
<body>
    
    <h1>Listar actividades</h1><br><br>

('monitor', 'actividad_Realizada', 'obs', 'fecha', )

    {% if datosAc %}
    <table>
        <thead>
            <tr>
                <td>Monitor</td>
                <td>Actividad realizada</td>
                <td>Comentarios</td>
                <td>Fecha monitoria</td>
            </tr>
        </thead>
        <tbody>
            {% for i in datosAc %}
            <tr>
                <td>{{i.monitor}}</td>
            </tr>
        </tbody>
    </table>

</body>
</html>

sena/territorio/templates/territorio/aprendiz/formAprendiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>

    <h1>Formulario aprendices</h1><br>
    <form action="{% url 'territorio:guardarAprendices' %}" method="post">

        {% csrf_token %}

        <label>Cedula</label><br>
        <input type="text" name="cedula" placeholder="1001..."><br><br>

        <label>Nombre</label><br>
        <input type="text" name="nombre" placeholder="Juanito"><br><br>

        <label>Apellido</label><br>
        <input type="text"  name="apellido" placeholder="Perez"><br><br>

        <label>Fecha de nacimiento</label><br>
        <input type="date" name="fecha_nacimiento"><br><br>

        <button type="submit">Guardar</button>

    </form>
    
</body>
</html>

sena/territorio/templates/territorio/aprendiz/listarAprendiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar aprendices</title>
</head>
<body>
    <h1 style="text-align: center">Aprendiz</h1><br>
    <h3 style="text-align: center"><a href="{% url 'territorio:crearAprendices' %}">Nuevo aprendiz</a></h3> <br>
    <h3 style="text-align: center"><a href="{% url 'territorio:index' %}">Inicio</a></h3><br>

    {% if datos %}
        <table border="1" width="50%" style="margin: auto; text-align: center;">
            <thead>
                <tr>
                    <th>id</th>
                    <th>cedula</th>
                    <th>nombre</th>
                    <th>apellido</th>
                    <th>fecha de nacimiento</th>  
                </tr>
            </thead>
            <tbody>
                {% for registro in datos%}
                    <tr>
                        <td>{{ registro.id }}</td>
                        <td>{{ registro.cedula}}</td>
                        <td>{{ registro.nombre}}</td>
                        <td>{{ registro.apellido}}</td>
                        <td>{{ registro.fecha_nacimiento}}</td>
                    </tr> <br/>
                {% endfor%}
            </tbody>
        </table>

    {% else%}
        <h1>No hay datos</h1>
    {% endif %}
</body>
</html>

sena/territorio/templates/territorio/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'territorio/css/style.css'%}">
    <title>Terrritorio Sena</title>
</head>
<body>
    <h1>Bienvenidos a territorio</h1>
    <a href="{% url 'territorio:listar-aprendices' %}">Aprendiz</a><br>
    <a href="{% url 'territorio:listar-monitoria' %}">Monitorias</a><br>
    <a href="{% url 'territorio:listar-actividades'%}">Actividades</a><br>
    <br><br>
    <img src="{% static 'territorio/img/images.jpeg' %}" alt="">
    <script src="{% static 'territorio/js/funciones.js' %}"></script>
</body>
</html>

sena/territorio/templates/territorio/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="{% url 'territorio:login' %}" method="post">
        {% csrf_token %}
        <label for="">Usuario</label><br>
        <input type="text" name="usuario"> <br><br>
        <label for="">Contraseña</label><br>
        <input type="password" name="clave"><br><br>
    
        <button type="submit">Enviar</button>
        <button><a href="{% url 'territorio:inicio' %}">Volver</a></button>
    </form>
</body>
</html>

sena/territorio/templates/territorio/monitoria/formMonitoria.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario monitoria</title>
</head>
<body>
    
    <h1>Formulario monitorias</h1>

    <form action="{% url 'territorio:monitoriasGuardar'%}" method="post">
 
        {% csrf_token %}

        <label for="">Categoria</label><br>
        <input type="text" name="cat" placeholder="Adsi"><br><br>

        <label for="">Nombre aprendiz</label><br>
        <select name="aprendiz">
            {% if datos%}
                {% for r in datos %}
                    <option value="{{r.id}}">{{r.nombre}}</option>
                {% endfor %}
            {% endif %}
        </select><br><br>

        <label for="">Fecha inicio</label><br>
        <input type="datetime-local" name="fecha_Inicio"><br><br>

        <label for="">Fecha fin</label><br>
        <input type="datetime-local" name="fecha_Final"><br><br>

        <button type="submit">Guardar</button>
    </form>

</body>
</html>

sena/territorio/templates/territorio/monitoria/listarMonitoria.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar monitorias</title>
</head>
<body>

    <h1>Monitorias</h1><br>

    <a href="{% url 'territorio:crearMonitoria'%}">Crear monitoria</a><br>
    <a href="{% url 'territorio:index' %}">Inicio</a><br>

    {% if datosM %}

        <table border="1" width="50%">
            <thead>
                <tr>
                    <td>Categoria</td>
                    <td>Aprendiz</td>
                    <td>Fecha de inicio</td>
                    <td>Fecha de fin</td>
                </tr>
            </thead>
            <tbody>
                {% for i in datosM %}
                    <tr>
                        <td>{{ i.cat}}</td>
                        <td>{{ i.aprendiz.nombre}}</td>
                        <td>{{ i.fecha_Inicio }}</td>
                        <td>{{ i.fecha_Final}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h3>No hay datos de las monitorias</h3>
    {% endif %}
</body>
</html>